remote_theme: cotes2020/jekyll-theme-chirpy
title: TerrariumPI Documentation
description: Here you can find the documentation for installation and operating TerrariumPI
avatar: /assets/images/profile_image.jpg
tagline: Reptile enclosure automation

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: TheYOSH
  email: terrariumpi@theyosh.nl             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/theyosh       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/theyosh

toc: true
