remote_theme: cotes2020/jekyll-theme-chirpy
title: TerrariumPI Documentation
description: Here you can find the documentation for installation and operating TerrariumPI
avatar: /assets/images/profile_image.jpg
tagline: Reptile enclosure automation
github:
  username: theyosh
