remote_theme: cotes2020/jekyll-theme-chirpy
title: TerrariumPI
description: Here you can find the documentation for installation and operating TerrariumPI
avatar: /assets/images/profile_image.jpg
tagline: Reptile enclosure automation
baseurl: 'TerrariumPI/'

github:
  username: theyosh             # change to your github username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: TheYOSH
  email: terrariumpi@theyosh.nl             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/theyosh       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/theyosh

toc: true

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.
