# This is a basic workflow to help you get started with Actions
name: Svelte GUI builder

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - svelte
    paths:
      - 'gui/**'
      - '*.json'
      - '**/*.js'

#  pull_request:
#    branches: [ master ]

#    paths-ignore:
#      - .gitignore
#      - README.md
#      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  continuous-delivery:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0  # for posts's lastmod

      - name: Use Node.js 16 LTS
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '16'

      - name: Install NPM Modules
        run: npm install && ./gui/patch.sh

      - name: Build Project
        run: npm run build

      - name: Commit GUI build
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -f public/*
          git commit -am "New Svelte GUI build" --author="theyosh <theyosh@users.noreply.github.com>"
          git push -f


        # uses: stefanzweifel/git-auto-commit-action@v4
        # with:
        #   # Optional. Option used by `git-status` to determine if the repository is
        #   # dirty. See https://git-scm.com/docs/git-status#_options
        #   # status_options: '--untracked-files=no'

        #   # Optional. Disable dirty check and always try to create a commit and push
        #   skip_dirty_check: true

        #   # Optional. Skip internal call to `git fetch`
        #   skip_fetch: true

        #   # Optional. Skip internal call to `git checkout`
        #   skip_checkout: true

        #   # Optional. Options used by `git-add`.
        #   # See https://git-scm.com/docs/git-add#_options
        #   add_options: '-u'
